### ISSUE TITLE
Documented the methods in DBWrapper 

### ISSUE THREAD

**Issue by coderbdsust** [SakibulMowla/catch-up#55]
- All the methods which access the data from database need to be documented for better understandings.

**Comment by SakibulMowla** [comment]
Official [Getting Started with Node.js and DynamoDB
](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html) is what I was referring to while writing the code. It's a good starting point. It doesn't contain documentation on how to make batch request and request/response syntax. Those documentation are available are [API reference](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations_Amazon_DynamoDB.html).

Maybe we can mention these 2 links at the top of DBWrapper or in README.?

DBWrapper itself doesn't do much other than adding a thin layer of sending the request to dynamodb, receiving response and logging inside catch in case of any error.

**Comment by coderbdsust** [comment]
Making a good readme file would be good. I was looking some good documentation. Thanks for the link
